set(PH_B2D_PATH "${PH_EXTERNALS}/${PH_B2D_PATH}/box2d/Box2D")
set(PH_B2D_SRCS
  ${PH_B2D_PATH}/Box2D/Collision/b2BroadPhase.cpp
  ${PH_B2D_PATH}/Box2D/Collision/b2CollideCircle.cpp
  ${PH_B2D_PATH}/Box2D/Collision/b2CollidePolygon.cpp
  ${PH_B2D_PATH}/Box2D/Collision/b2Collision.cpp
  ${PH_B2D_PATH}/Box2D/Collision/b2Distance.cpp
  ${PH_B2D_PATH}/Box2D/Collision/b2DynamicTree.cpp
  ${PH_B2D_PATH}/Box2D/Collision/b2TimeOfImpact.cpp
  ${PH_B2D_PATH}/Box2D/Collision/Shapes/b2CircleShape.cpp
  ${PH_B2D_PATH}/Box2D/Collision/Shapes/b2PolygonShape.cpp
  ${PH_B2D_PATH}/Box2D/Common/b2BlockAllocator.cpp
  ${PH_B2D_PATH}/Box2D/Common/b2Math.cpp
  ${PH_B2D_PATH}/Box2D/Common/b2Settings.cpp
  ${PH_B2D_PATH}/Box2D/Common/b2StackAllocator.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/b2Body.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/b2ContactManager.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/b2Fixture.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/b2Island.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/b2World.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/b2WorldCallbacks.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/Contacts/b2CircleContact.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/Contacts/b2Contact.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/Contacts/b2ContactSolver.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/Contacts/b2PolygonContact.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/Contacts/b2TOISolver.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2DistanceJoint.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2FrictionJoint.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2GearJoint.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2Joint.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2LineJoint.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2MouseJoint.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2PrismaticJoint.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2PulleyJoint.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2RevoluteJoint.cpp
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2WeldJoint.cpp
  )

set(PH_B2D_HEADERS
  ${PH_B2D_PATH}/Box2D/Box2D.h
  ${PH_B2D_PATH}/Box2D/Collision/b2BroadPhase.h
  ${PH_B2D_PATH}/Box2D/Collision/b2Collision.h
  ${PH_B2D_PATH}/Box2D/Collision/b2Distance.h
  ${PH_B2D_PATH}/Box2D/Collision/b2DynamicTree.h
  ${PH_B2D_PATH}/Box2D/Collision/b2TimeOfImpact.h
  ${PH_B2D_PATH}/Box2D/Collision/Shapes/b2CircleShape.h
  ${PH_B2D_PATH}/Box2D/Collision/Shapes/b2PolygonShape.h
  ${PH_B2D_PATH}/Box2D/Collision/Shapes/b2Shape.h
  ${PH_B2D_PATH}/Box2D/Common/b2BlockAllocator.h
  ${PH_B2D_PATH}/Box2D/Common/b2Math.h
  ${PH_B2D_PATH}/Box2D/Common/b2Settings.h
  ${PH_B2D_PATH}/Box2D/Common/b2StackAllocator.h
  ${PH_B2D_PATH}/Box2D/Dynamics/b2Body.h
  ${PH_B2D_PATH}/Box2D/Dynamics/b2ContactManager.h
  ${PH_B2D_PATH}/Box2D/Dynamics/b2Fixture.h
  ${PH_B2D_PATH}/Box2D/Dynamics/b2Island.h
  ${PH_B2D_PATH}/Box2D/Dynamics/b2TimeStep.h
  ${PH_B2D_PATH}/Box2D/Dynamics/b2World.h
  ${PH_B2D_PATH}/Box2D/Dynamics/b2WorldCallbacks.h
  ${PH_B2D_PATH}/Box2D/Dynamics/Contacts/b2CircleContact.h
  ${PH_B2D_PATH}/Box2D/Dynamics/Contacts/b2Contact.h
  ${PH_B2D_PATH}/Box2D/Dynamics/Contacts/b2ContactSolver.h
  ${PH_B2D_PATH}/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.h
  ${PH_B2D_PATH}/Box2D/Dynamics/Contacts/b2PolygonContact.h
  ${PH_B2D_PATH}/Box2D/Dynamics/Contacts/b2TOISolver.h
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2DistanceJoint.h
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2FrictionJoint.h
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2GearJoint.h
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2Joint.h
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2LineJoint.h
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2MouseJoint.h
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2PrismaticJoint.h
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2PulleyJoint.h
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2RevoluteJoint.h
  ${PH_B2D_PATH}/Box2D/Dynamics/Joints/b2WeldJoint.h
  )

include(${PH_ENGINE_PATH}/scripts/Box2D_IncludeDirs.cmake)
