print(gameManager:className())
gameManager:setShowsFPS(true)
print(gameManager:setUpNavigationController():className())
print(gameManager:mainDrawable():className())
print(gameManager:framesPerSecond())
