set(SRCS
  Core/PHAccelInterface.cpp
  Core/PHFontInitPool.cpp
  Core/PHLuaObject.cpp
  Core/PHAnimatedImage.cpp
  Core/PHGLProgramInitPool.cpp
  Core/PHMessage.cpp
  Core/PHAnimator.cpp
  Core/PHGLShader.cpp
  Core/PHMotion.cpp
  Core/PHAnimatorPool.cpp
  Core/PHGLShaderProgram.cpp
  Core/PHNavigationController.cpp
  Core/PHAuxLayerView.cpp
  Core/PHGLUniformStates.cpp
  Core/PHNormalImage.cpp
  Core/PHBezierPath.cpp
  Core/PHGLVertexArrayObject.cpp
  Core/PHParticleAnimator.cpp
  Core/PHCinematicActor.cpp
  Core/PHGLVertexBufferObject.cpp   
  Core/PHParticleView.cpp
  Core/PHCinematicAnimator.cpp
  Core/PHGameManager.cpp
  Core/PHCurve.cpp
  Core/PHImage.cpp
  Core/PHStripeCurve.cpp
  Core/PHDeferredView.cpp
  Core/PHImageAnimator.cpp
  Core/PHTextView.cpp
  Core/PHErrors.cpp
  Core/PHImageInitPool.cpp
  Core/PHThread.cpp
  Core/PHEvent.cpp
  Core/PHImageView.cpp
  Core/PHTime.cpp
  Core/PHEventHandler.cpp
  Core/PHKeyframeAnimator.cpp
  Core/PHTimer.cpp
  Core/PHEventQueue.cpp
  Core/PHKeyframeAnimatorGroup.cpp
  Core/PHTrailImageView.cpp
  Core/PHFileManager.cpp
  Core/PHLua.cpp
  Core/PHView.cpp
  Core/PHFont.cpp
  Core/PHViewController.cpp
  Geometry/PHColor.cpp
  Geometry/PHMatrix.cpp
  Geometry/PHRange.cpp
  Geometry/PHGeometry.cpp
  Geometry/PHPoint.cpp
  Geometry/PHRect.cpp
  UI/PHButtonView.cpp
  UI/PHTestViewController.cpp
  UI/PHTextControllerView.cpp
  UI/PHTestView.cpp
  UI/PHTextController.cpp
  Network/PHLuaConsole.cpp
  Network/PHRemote.cpp
  Network/PHTCPConsole.cpp
  Network/PHTCPServer.cpp
  ${PH_EXTERNALS}/uremote/src/URClient.cpp
  ${PH_EXTERNALS}/uremote/src/URCommon.cpp
  ${PH_EXTERNALS}/uremote/src/URField.cpp
  ${PH_EXTERNALS}/uremote/src/URServer.cpp
  )

set(INCLUDES )

include_directories(
  ${CMAKE_CURRENT_SOURCE_DIR}/Core 
  ${CMAKE_CURRENT_SOURCE_DIR}/Geometry
  ${CMAKE_CURRENT_SOURCE_DIR}/Sound
  ${CMAKE_CURRENT_SOURCE_DIR}/UI
  ${CMAKE_CURRENT_SOURCE_DIR}/Network
  ${PH_EXTERNALS}/lua/src
  ${PH_EXTERNALS}/libpng
  ${PH_EXTERNALS}/zlib
  ${PH_EXTERNALS}/uremote/include
  )